CREATE USER hr IDENTIFIED BY hr;
ALTER USER hr DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
ALTER USER hr TEMPORARY TABLESPACE TEMP;
GRANT CREATE SESSION, CREATE VIEW, ALTER SESSION, CREATE SEQUENCE TO hr;
GRANT CREATE SYNONYM, CREATE DATABASE LINK, RESOURCE TO hr;


 --
GRANT CONNECT,RESOURCE,UNLIMITED TABLESPACE TO SCOTT IDENTIFIED BY TIGER;
ALTER USER SCOTT DEFAULT TABLESPACE USERS;
ALTER USER SCOTT TEMPORARY TABLESPACE TEMP;